### ISSUE TITLE
Local wifi pairing

### ISSUE THREAD

**Issue by bit111** [mac-zhou/midea-msmart#6]
Hello,
is there a way to pair climate with my wifi network in local mode, without to use app (and its cloud)?

**Comment by 0xbw** [comment]
No, I suggest that you can prevent the device from accessing the Internet after pairing

mac_zhou

在 2020年5月25日，21:17，bit111 <notifications@github.com> 写道：


Hello,
is there a way to pair climate with my wifi network in local mode, without to use app (and its cloud)?

**Comment by bit111** [comment]
Ok, thanks.
So, can you tell me where I can find a tutorial to use your lib (eg. set temperature, move fan, etc.)?
Thanks.

**Comment by 0xbw** [comment]
if you use home assistant, you can use (https://github.com/mac-zhou/midea-ac-py) 
or you can write code like this #5

**Comment by bit111** [comment]
> if you use home assistant, you can use (https://github.com/mac-zhou/midea-ac-py)

It was exactly what I was looking for!

**Comment by Hypfer** [comment]
Looking at the SDK docs, it should probably be possible to send whatever `MSmartUserDeviceManager.startConfigureDevice` sends to provision the climate device.

I'd assume that it's using the same local interface used for controling the device?

**Comment by Hypfer** [comment]
As it turns out, the official app uses http which means that we can easily spin up a mock server.

This way it is possible to provision the device without using the cloud at all 🎉

**Comment by kueblc** [comment]
@Hypfer were you able to get anywhere with this? I'm interested in doing this too

**Comment by Hypfer** [comment]
@kueblc 

I didn't try local communication since my goal was to replace the cloud. While decryption of the first few cloud messages works, it seems like they're doing some kind of handshake there to get a session key or something.
After that, I wasn't able to decrypt further communication.

Since it's a replaceable USB dongle, it might make sense to just ditch it altogether and build a replacement.

https://community.home-assistant.io/t/any-support-for-midea-a-c/18742/151
According to this post it's possible but there wasn't any answer since that.

I tried attaching the dongle to multiple USB controllers. none of them recognized it so maybe it's just the USB form factor but actually speaks UART on the data pins? 

If you feel like it, i'd suggest adding a logic analyzer there to take a look at what's happening.
You could use some cheap usb extension cord so that you don't have to solder stuff onto the USB dongle

**Comment by kueblc** [comment]
Thanks for your quick response @Hypfer.

My goal is also to replace the cloud, but without physically disassembling the air conditioner. While it looks like @mac-zhou has reverse engineered most of the control over local communication, he still requires that you do the initial provisioning with the cloud. I'm interested in replacing this step with a local mock cloud and replicating the mechanism of the app, as you mentioned.

I started taking a look into the Android app and came to the same conclusion you did, that `MSmartUserDeviceManager.startConfigureDevice` is the entry point for whatever the app is doing to provision the device. This is how I found this issue thread. The obfuscated code is pretty dense however, so it's taking me some time to figure out. I was hoping that you could share your findings so far so that I don't end up repeating work.

It might be easier to understand if I could listen in on a device being provisioned, but as I do not want to connect my device to the cloud even once (in addition to sharing my information, it could potentially force a firmware update), I have no real world data to work from. If you have any captures of the provisioning process, would you mind sharing these as well?

**Comment by Hypfer** [comment]
@kueblc 

I cannot share provisioning data since that would mean sharing my wifi credentials.

You can however use this mock backend to provision it yourself without any cloud access.
Be aware though that this is extremely hackish code.

[mideamock.zip](https://github.com/mac-zhou/midea-msmart/files/4907256/mideamock.zip)

I've used the Midea app Version 5.0.2.605 and redirected all the traffic to the mock backend via my router:

```
/etc/dnsmasq.d$ cat midea.conf
address=/appsmb.com/10.1.2.3
address=/www.appsmb.com/10.1.2.3
address=/mapp.appsmb.com/10.1.2.3
address=/app.appsmb.com/10.1.2.3
address=/jump.appsmb.com/10.1.2.3
address=/module.appsmb.com/10.1.2.3
address=/mapptest.appsmb.com/10.1.2.3
address=/midea.com/10.1.2.3
address=/www.midea.com/10.1.2.3
address=/qrcode.midea.com/10.1.2.3
address=/obm.midea.com/10.1.2.3
address=/air.midea.com/10.1.2.3
address=/airtest.midea.com/10.1.2.3
```

You can log-in with anything and then simply follow the provisioning procedure.

Furthermore, there are a few real messages in the testMideaMsg.js class.

Ignore the `Header for switch-on/off & query-status command` and `Header for non-power-related command`
Thats wrong. They don't differ at all apart from timestamps.

**Comment by kueblc** [comment]
Thanks very much @Hypfer, I really appreciate you sharing your work so far. I will be sure to post back with any new findings.

**Comment by 0xbw** [comment]
Actually, I probably know how to do it.
But I am now mainly focused on the decryption of new network protocols.
Because after disconnecting the cloud, I must ensure that the local communication is normal.

**Comment by 0xbw** [comment]
i created a telegram group https://t.me/joinchat/BhU6LRytPXLsiqTIar0jqg 7
So that everyone can communicate better :joy:

**Comment by 0xbw** [comment]
I provide an easy way
After power off and restart, track DNS requests of midea devices
You will find 1 DNS request. After shielding this domain name resolution, the cloud is disconnected.
For example, on my side: iot1.midea.com.cn
